# Clear php alpine image
FROM python:alpine
RUN apk update \
&& apk add tzdata \
&& cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime \
&& echo "Europe/Moscow" >  /etc/timezone
CMD echo 'IMAGE CREATED'
